name: CI - Test & Lint

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  
    steps:
      - name: Checkout репозиторій
        uses: actions/checkout@v4

      - name: Налаштування Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  

      - name: Встановлення залежностей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Якщо є requirements.txt
          pip install pytest flake8  # Бібліотеки для тестування і перевірки стилю

      - name: Запуск тестів
        run: pytest

      - name: Перевірка коду за PEP8 (flake8)
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
